/*
 * TodoList RESTful API
 * OpenAPI for Todolist RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: armandwi.pangestu7@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Todolist from './Todolist';

/**
 * The ArrayTodolist model module.
 * @module model/ArrayTodolist
 * @version 1.0.0
 */
export default class ArrayTodolist extends Array {
  /**
   * Constructs a new <code>ArrayTodolist</code>.
   * @alias module:model/ArrayTodolist
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>ArrayTodolist</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ArrayTodolist} obj Optional instance to populate.
   * @return {module:model/ArrayTodolist} The populated <code>ArrayTodolist</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ArrayTodolist();
      ApiClient.constructFromObject(data, obj, 'Todolist');
    }
    return obj;
  }
}
